import {
  formatCurrency,
  formatNumber,
  formatPercent,
} from "@/lib/waitwise/formatters";
import type { Inputs } from "@/lib/waitwise/types";

type ConfidenceLevel =
  | "High confidence"
  | "Medium confidence"
  | "Low confidence";

type AssumptionMetaEntry = {
  label: string;
  unit: string;
  formatter: (value: number | string) => string;
  description: string;
  source_type: string;
  confidence: ConfidenceLevel;
};

export const ASSUMPTION_META: Record<keyof Inputs, AssumptionMetaEntry> = {
  starting_waiting_list_size: {
    label: "Starting waiting list size",
    unit: "patients",
    formatter: (x) => formatNumber(Number(x)),
    description: "Estimated number of patients on the waiting list at baseline.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  monthly_inflow: {
    label: "Monthly inflow",
    unit: "patients",
    formatter: (x) => formatNumber(Number(x)),
    description: "Estimated new demand entering the waiting list each month.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  baseline_monthly_throughput: {
    label: "Baseline monthly throughput",
    unit: "patients",
    formatter: (x) => formatNumber(Number(x)),
    description: "Estimated baseline number of patients processed each month.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  average_wait_duration_months: {
    label: "Average wait duration proxy",
    unit: "months",
    formatter: (x) => Number(x).toFixed(1),
    description:
      "Simple proxy for typical waiting time before treatment or review.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },

  intervention_reach_rate: {
    label: "Base intervention reach rate",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description:
      "Estimated share of the waiting list that the intervention could reach before any targeting adjustment is applied.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  target_population_multiplier: {
    label: "Target population multiplier",
    unit: "x",
    formatter: (x) => `${Number(x).toFixed(2)}x`,
    description:
      "Scales the size of the population included in the intervention scenario. Lower values represent a narrower targeted subgroup.",
    source_type: "User override",
    confidence: "Medium confidence",
  },
  target_reach_multiplier: {
    label: "Target reach multiplier",
    unit: "x",
    formatter: (x) => `${Number(x).toFixed(2)}x`,
    description:
      "Scales the effective reach rate within the targeted group. Values above 1 imply the targeted population is easier to reach.",
    source_type: "User override",
    confidence: "Medium confidence",
  },
  target_escalation_risk_multiplier: {
    label: "Target escalation risk multiplier",
    unit: "x",
    formatter: (x) => `${Number(x).toFixed(2)}x`,
    description:
      "Scales the baseline escalation risk for the targeted group. Values above 1 imply risk is more concentrated in the selected population.",
    source_type: "User override",
    confidence: "Medium confidence",
  },

  demand_reduction_effect: {
    label: "Demand reduction effect",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description:
      "Estimated reduction in incoming demand generated by the intervention.",
    source_type: "Illustrative default",
    confidence: "Low confidence",
  },
  throughput_increase_effect: {
    label: "Throughput increase effect",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description:
      "Estimated increase in throughput generated by the intervention.",
    source_type: "Illustrative default",
    confidence: "Low confidence",
  },
  escalation_reduction_effect: {
    label: "Escalation reduction effect",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description:
      "Estimated reduction in deterioration or escalation while waiting.",
    source_type: "Illustrative default",
    confidence: "Low confidence",
  },

  intervention_cost_per_patient_reached: {
    label: "Intervention cost per patient reached",
    unit: "GBP",
    formatter: (x) => formatCurrency(Number(x)),
    description:
      "Estimated cost of the intervention for each patient reached.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  effect_decay_rate: {
    label: "Annual effect decay",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description: "Estimated annual reduction in intervention effect over time.",
    source_type: "Illustrative default",
    confidence: "Low confidence",
  },
  participation_dropoff_rate: {
    label: "Annual participation drop-off",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description:
      "Estimated annual reduction in effective intervention reach over time.",
    source_type: "Illustrative default",
    confidence: "Low confidence",
  },

  monthly_escalation_rate: {
    label: "Monthly escalation rate while waiting",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description:
      "Estimated proportion of the waiting list that deteriorates or escalates each month before targeting adjustment.",
    source_type: "Evidence-informed proxy",
    confidence: "Medium confidence",
  },
  admission_rate_after_escalation: {
    label: "Admission rate after escalation",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description: "Estimated share of escalations leading to admission.",
    source_type: "Evidence-informed proxy",
    confidence: "Medium confidence",
  },
  average_length_of_stay: {
    label: "Average length of stay",
    unit: "days",
    formatter: (x) => Number(x).toFixed(1),
    description: "Average inpatient length of stay after admission.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  qaly_gain_per_escalation_avoided: {
    label: "QALY gain per escalation avoided",
    unit: "QALYs",
    formatter: (x) => Number(x).toFixed(2),
    description:
      "Estimated quality-of-life gain from preventing an escalation while waiting.",
    source_type: "Evidence-informed proxy",
    confidence: "Low confidence",
  },

  cost_per_escalation: {
    label: "Cost per escalation",
    unit: "GBP",
    formatter: (x) => formatCurrency(Number(x)),
    description:
      "Estimated unit cost associated with deterioration or escalation while waiting.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  cost_per_admission: {
    label: "Cost per admission",
    unit: "GBP",
    formatter: (x) => formatCurrency(Number(x)),
    description: "Estimated cost per admission generated by escalation.",
    source_type: "Operational estimate",
    confidence: "Medium confidence",
  },
  cost_per_bed_day: {
    label: "Cost per bed day",
    unit: "GBP",
    formatter: (x) => formatCurrency(Number(x)),
    description:
      "Illustrative value of an inpatient bed day for exploratory costing.",
    source_type: "Illustrative default",
    confidence: "Low confidence",
  },
  costing_method: {
    label: "Costing method",
    unit: "",
    formatter: (x) => String(x),
    description:
      "Method used to value the economic effect of reduced waiting list pressure.",
    source_type: "User override",
    confidence: "Medium confidence",
  },

  time_horizon_years: {
    label: "Time horizon",
    unit: "years",
    formatter: (x) => `${Number(x)}`,
    description: "Number of years over which costs and benefits are modelled.",
    source_type: "User override",
    confidence: "High confidence",
  },
  discount_rate: {
    label: "Discount rate",
    unit: "%",
    formatter: (x) => formatPercent(Number(x)),
    description: "Annual rate used to discount future costs and QALYs.",
    source_type: "Evidence-informed proxy",
    confidence: "High confidence",
  },
  cost_effectiveness_threshold: {
    label: "Cost-effectiveness threshold",
    unit: "GBP per QALY",
    formatter: (x) => formatCurrency(Number(x)),
    description:
      "Illustrative threshold used to interpret discounted cost per QALY.",
    source_type: "Illustrative default",
    confidence: "High confidence",
  },
};

export const ASSUMPTION_ORDER: (keyof Inputs)[] = [
  "starting_waiting_list_size",
  "monthly_inflow",
  "baseline_monthly_throughput",
  "average_wait_duration_months",
  "intervention_reach_rate",
  "target_population_multiplier",
  "target_reach_multiplier",
  "target_escalation_risk_multiplier",
  "demand_reduction_effect",
  "throughput_increase_effect",
  "escalation_reduction_effect",
  "intervention_cost_per_patient_reached",
  "effect_decay_rate",
  "participation_dropoff_rate",
  "monthly_escalation_rate",
  "admission_rate_after_escalation",
  "average_length_of_stay",
  "qaly_gain_per_escalation_avoided",
  "cost_per_escalation",
  "cost_per_admission",
  "cost_per_bed_day",
  "costing_method",
  "time_horizon_years",
  "discount_rate",
  "cost_effectiveness_threshold",
];

export function getAssumptionConfidenceSummary(): Record<
  ConfidenceLevel | "summary_text",
  number | string
> {
  const summary: Record<ConfidenceLevel, number> = {
    "High confidence": 0,
    "Medium confidence": 0,
    "Low confidence": 0,
  };

  Object.values(ASSUMPTION_META).forEach((meta) => {
    summary[meta.confidence] += 1;
  });

  return {
    ...summary,
    summary_text: `${summary["High confidence"]} high-confidence, ${summary["Medium confidence"]} medium-confidence, and ${summary["Low confidence"]} low-confidence assumptions are currently in play.`,
  };
}