from utils.formatters import (
    format_currency,
    format_number,
    format_percent,
)


ASSUMPTION_META = {
    "starting_waiting_list_size": {
        "label": "Starting waiting list size",
        "unit": "patients",
        "formatter": format_number,
        "description": "Estimated number of patients on the waiting list at baseline.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "monthly_inflow": {
        "label": "Monthly inflow",
        "unit": "patients",
        "formatter": format_number,
        "description": "Estimated new demand entering the waiting list each month.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "baseline_monthly_throughput": {
        "label": "Baseline monthly throughput",
        "unit": "patients",
        "formatter": format_number,
        "description": "Estimated baseline number of patients processed each month.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "average_wait_duration_months": {
        "label": "Average wait duration proxy",
        "unit": "months",
        "formatter": lambda x: f"{x:,.1f}",
        "description": "Simple proxy for typical waiting time before treatment or review.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "intervention_reach_rate": {
        "label": "Intervention reach rate",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated share of the waiting list effectively reached by the intervention.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "demand_reduction_effect": {
        "label": "Demand reduction effect",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated reduction in incoming demand generated by the intervention.",
        "source_type": "Illustrative default",
        "confidence": "Low confidence",
    },
    "throughput_increase_effect": {
        "label": "Throughput increase effect",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated increase in throughput generated by the intervention.",
        "source_type": "Illustrative default",
        "confidence": "Low confidence",
    },
    "escalation_reduction_effect": {
        "label": "Escalation reduction effect",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated reduction in deterioration or escalation while waiting.",
        "source_type": "Illustrative default",
        "confidence": "Low confidence",
    },
    "intervention_cost_per_patient_reached": {
        "label": "Intervention cost per patient reached",
        "unit": "GBP",
        "formatter": format_currency,
        "description": "Estimated cost of the intervention for each patient reached.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "effect_decay_rate": {
        "label": "Annual effect decay",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated annual reduction in intervention effect over time.",
        "source_type": "Illustrative default",
        "confidence": "Low confidence",
    },
    "participation_dropoff_rate": {
        "label": "Annual participation drop-off",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated annual reduction in effective intervention reach over time.",
        "source_type": "Illustrative default",
        "confidence": "Low confidence",
    },
    "monthly_escalation_rate": {
        "label": "Monthly escalation rate while waiting",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated proportion of the waiting list that deteriorates or escalates each month.",
        "source_type": "Evidence-informed proxy",
        "confidence": "Medium confidence",
    },
    "admission_rate_after_escalation": {
        "label": "Admission rate after escalation",
        "unit": "%",
        "formatter": format_percent,
        "description": "Estimated share of escalations leading to admission.",
        "source_type": "Evidence-informed proxy",
        "confidence": "Medium confidence",
    },
    "average_length_of_stay": {
        "label": "Average length of stay",
        "unit": "days",
        "formatter": lambda x: f"{x:,.1f}",
        "description": "Average inpatient length of stay after admission.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "qaly_gain_per_escalation_avoided": {
        "label": "QALY gain per escalation avoided",
        "unit": "QALYs",
        "formatter": lambda x: f"{x:.2f}",
        "description": "Estimated quality-of-life gain from preventing an escalation while waiting.",
        "source_type": "Evidence-informed proxy",
        "confidence": "Low confidence",
    },
    "cost_per_escalation": {
        "label": "Cost per escalation",
        "unit": "GBP",
        "formatter": format_currency,
        "description": "Estimated unit cost associated with deterioration or escalation while waiting.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "cost_per_admission": {
        "label": "Cost per admission",
        "unit": "GBP",
        "formatter": format_currency,
        "description": "Estimated cost per admission generated by escalation.",
        "source_type": "Operational estimate",
        "confidence": "Medium confidence",
    },
    "cost_per_bed_day": {
        "label": "Cost per bed day",
        "unit": "GBP",
        "formatter": format_currency,
        "description": "Illustrative value of an inpatient bed day for exploratory costing.",
        "source_type": "Illustrative default",
        "confidence": "Low confidence",
    },
    "costing_method": {
        "label": "Costing method",
        "unit": "",
        "formatter": lambda x: x,
        "description": "Method used to value the economic effect of reduced waiting list pressure.",
        "source_type": "User override",
        "confidence": "Medium confidence",
    },
    "targeting_mode": {
        "label": "Targeting mode",
        "unit": "",
        "formatter": lambda x: x,
        "description": "How broadly or narrowly the intervention is focused across the waiting list.",
        "source_type": "User override",
        "confidence": "Medium confidence",
    },
    "time_horizon_years": {
        "label": "Time horizon",
        "unit": "years",
        "formatter": lambda x: f"{int(x)}",
        "description": "Number of years over which costs and benefits are modelled.",
        "source_type": "User override",
        "confidence": "High confidence",
    },
    "discount_rate": {
        "label": "Discount rate",
        "unit": "%",
        "formatter": format_percent,
        "description": "Annual rate used to discount future costs and QALYs.",
        "source_type": "Evidence-informed proxy",
        "confidence": "High confidence",
    },
    "cost_effectiveness_threshold": {
        "label": "Cost-effectiveness threshold",
        "unit": "GBP per QALY",
        "formatter": format_currency,
        "description": "Illustrative threshold used to interpret discounted cost per QALY.",
        "source_type": "Illustrative default",
        "confidence": "High confidence",
    },
}


ASSUMPTION_ORDER = [
    "starting_waiting_list_size",
    "monthly_inflow",
    "baseline_monthly_throughput",
    "average_wait_duration_months",
    "intervention_reach_rate",
    "demand_reduction_effect",
    "throughput_increase_effect",
    "escalation_reduction_effect",
    "intervention_cost_per_patient_reached",
    "effect_decay_rate",
    "participation_dropoff_rate",
    "monthly_escalation_rate",
    "admission_rate_after_escalation",
    "average_length_of_stay",
    "qaly_gain_per_escalation_avoided",
    "cost_per_escalation",
    "cost_per_admission",
    "cost_per_bed_day",
    "costing_method",
    "targeting_mode",
    "time_horizon_years",
    "discount_rate",
    "cost_effectiveness_threshold",
]


def get_assumption_confidence_summary() -> dict:
    summary = {
        "High confidence": 0,
        "Medium confidence": 0,
        "Low confidence": 0,
    }

    for meta in ASSUMPTION_META.values():
        confidence = meta["confidence"]
        if confidence in summary:
            summary[confidence] += 1

    summary["summary_text"] = (
        f"{summary['High confidence']} high-confidence, "
        f"{summary['Medium confidence']} medium-confidence, and "
        f"{summary['Low confidence']} low-confidence assumptions are currently in play."
    )
    return summary
